<?php
declare(strict_types=1);
require __DIR__ . '/../config/bootstrap.php';
use Wisdom\Core\App; use Wisdom\Core\AppException; use Wisdom\Core\Csrf; use Wisdom\Core\Guard; use Wisdom\Core\ListQuery; use Wisdom\Core\Request; use Wisdom\Core\Session; use Wisdom\Services\UserService;
$admin=Guard::requirePermission('admin.access'); Guard::requirePasswordResetHandled(); $service=App::get(UserService::class); $active='admin-users'; $pageTitle='All users';
if(Request::isPost()){
    Guard::throttle('admin.action',60,60);
    if(!Csrf::verifyRequest()){Session::flash('error','Your session expired. Please try again.');redirect('admin-users.php');}
    try{if(!$admin->can('user.manage'))throw new AppException('You do not have permission to manage users.');$id=Request::intPost('user_id');switch(Request::post('form_action')){case 'user_active':$service->setActive($admin,$id,Request::post('active')==='1');Session::flash('success','Account status updated.');break;case 'user_delete':$service->delete($admin,$id);Session::flash('success','Account deleted.');break;default:throw new AppException('Unknown action.');}}catch(AppException $e){Session::flash('error',$e->getMessage());}
    $params=array_filter(['sort'=>Request::get('sort'),'dir'=>Request::get('dir'),'page'=>Request::get('page'),'f_role'=>Request::get('f_role'),'f_level'=>Request::get('f_level'),'f_status'=>Request::get('f_status'),'f_q'=>Request::get('f_q')],static fn(string $v):bool=>$v!=='');$qs=http_build_query($params);redirect('admin-users.php'.($qs===''?'':'?'.$qs));
}
$q=ListQuery::fromRequest(['id','name','email','created_at','role','level'],'created_at',20);$page=$service->page($q);
?><!doctype html><html lang="en"><head><?php require __DIR__.'/partials/head.php'; ?></head><body><div class="shell"><?php require __DIR__.'/partials/nav.php'; ?><main class="shell__main page-fade"><?php require __DIR__.'/partials/notice.php'; ?><?php require __DIR__.'/partials/admin_flash.php'; ?><header style="margin-bottom:var(--s-8)"><div class="eyebrow">Directory</div><h1>All users</h1><p class="text-muted"><?= (int)$page['total'] ?> users on file.</p></header>
<form method="get" class="filter-bar" action="admin-users.php"><input type="hidden" name="sort" value="<?= e($q->sort) ?>"><input type="hidden" name="dir" value="<?= e($q->dir) ?>"><div class="field"><label for="f_role">Role</label><select id="f_role" name="f_role"><option value="">All roles</option><?php foreach(['student','secretary','admin'] as $r): ?><option value="<?= e($r) ?>" <?= $q->filter('role')===$r?'selected':'' ?>><?= e(ucfirst($r)) ?></option><?php endforeach; ?></select></div><div class="field"><label for="f_level">Programme</label><select id="f_level" name="f_level"><option value="">All programmes</option><?php foreach(\Wisdom\Models\User::LEVELS as $l): ?><option value="<?= e($l) ?>" <?= $q->filter('level')===$l?'selected':'' ?>><?= e($l) ?></option><?php endforeach; ?></select></div><div class="field"><label for="f_status">Status</label><select id="f_status" name="f_status"><option value="">Any</option><?php foreach(['active','suspended','approved','pending'] as $s): ?><option value="<?= e($s) ?>" <?= $q->filter('status')===$s?'selected':'' ?>><?= e(ucfirst($s)) ?></option><?php endforeach; ?></select></div><div class="field"><label for="f_q">Search</label><input id="f_q" name="f_q" value="<?= e($q->filter('q')) ?>" placeholder="Name or email"></div><button class="btn">Apply</button><a class="btn btn--ghost" href="admin-users.php">Reset</a><?php if($admin->can('team.manage')): ?><a class="btn btn--gold" href="admin-add-user.php">Add user</a><?php endif; ?></form>
<div class="table-wrap"><table class="table"><thead><tr><?= sortable_th('Name','name',$q) ?><?= sortable_th('Email','email',$q) ?><th>Sex</th><?= sortable_th('Programme','level',$q) ?><th>Status</th><?= sortable_th('Role','role',$q) ?><?= sortable_th('Joined','created_at',$q) ?><?php if($admin->can('user.manage')): ?><th>Actions</th><?php endif; ?></tr></thead><tbody><?php if($page['rows']===[]): ?><tr><td colspan="8" class="text-muted">No users match those filters.</td></tr><?php else: foreach($page['rows'] as $u): ?><tr><td class="is-name"><?= e($u->getName()) ?></td><td class="is-email" title="<?= e($u->getEmail()) ?>"><?= e($u->getEmail()) ?></td><td><?= $u->isStaff()?'—':e((string)$u->getSex()) ?></td><td><?= $u->isStaff()?'—':e((string)$u->getLevel()) ?></td><td><span class="badge <?= $u->isApproved()?'badge--on':'badge--gold' ?>"><?= $u->isApproved()?'Approved':'Pending' ?></span> <span class="badge <?= $u->isActive()?'badge--on':'badge--off' ?>"><?= $u->isActive()?'Active':'Suspended' ?></span></td><td><?= e($u->roleLabel()) ?></td><td><?= e($u->getCreatedAt()) ?></td><?php if($admin->can('user.manage')): ?><td><?php if(!$u->isAdmin()): ?><div class="row gap-2"><form method="post" action="admin-users.php?<?= e(http_build_query($_GET)) ?>"><?= csrf_field() ?><input type="hidden" name="form_action" value="user_active"><input type="hidden" name="user_id" value="<?= (int)$u->getId() ?>"><input type="hidden" name="active" value="<?= $u->isActive()?'0':'1' ?>"><button class="btn btn--ghost btn--sm" type="submit"><?= $u->isActive()?'Suspend':'Reactivate' ?></button></form><form method="post" action="admin-users.php?<?= e(http_build_query($_GET)) ?>" data-confirm-modal data-modal-title="Delete this account?" data-modal-body="This permanently removes the account and related records." data-modal-confirm="Delete account" data-modal-danger="1"><?= csrf_field() ?><input type="hidden" name="form_action" value="user_delete"><input type="hidden" name="user_id" value="<?= (int)$u->getId() ?>"><button class="btn btn--danger btn--sm" type="submit">Delete</button></form></div><?php else: ?>Protected<?php endif; ?></td><?php endif; ?></tr><?php endforeach; endif; ?></tbody></table></div><?= render_pager($q,(int)$page['total']) ?></main></div><script src="assets/js/wisdom-ui.js" nonce="<?= e(nonce()) ?>" defer></script></body></html>
