<?php
declare(strict_types=1);
require __DIR__ . '/../config/bootstrap.php';
use Wisdom\Core\App; use Wisdom\Core\AppException; use Wisdom\Core\Csrf; use Wisdom\Core\Guard; use Wisdom\Core\ListQuery; use Wisdom\Core\Request; use Wisdom\Core\Session; use Wisdom\Services\PaymentService; use Wisdom\Services\SettingService;
$admin=Guard::requirePermission('admin.access'); Guard::requirePasswordResetHandled(); $payments=App::get(PaymentService::class); $settings=App::get(SettingService::class); $active='admin-payments'; $pageTitle='Fees verification';
if(Request::isPost()){
    Guard::throttle('admin.action',60,60);
    if(!Csrf::verifyRequest()){Session::flash('error','Your session expired. Please try again.');redirect('admin-payments.php');}
    try{switch(Request::post('form_action')){case 'payment_status':if(!$admin->can('payment.review'))throw new AppException('You do not have permission to review payments.');$payments->review($admin,Request::intPost('payment_id'),Request::post('status'));Session::flash('success','Payment decision recorded.');break;case 'save_payment_settings':if(!$admin->can('settings.manage'))throw new AppException('You do not have permission to change payment settings.');$settings->update($admin,[SettingService::KEY_BANK_NUMBER=>Request::post('bank_number'),SettingService::KEY_LIPA_NUMBER=>Request::post('lipa_number')]);Session::flash('success','Payment details updated.');break;default:throw new AppException('Unknown action.');}}catch(AppException $e){Session::flash('error',$e->getMessage());}
    redirect('admin-payments.php');
}
$q=ListQuery::fromRequest(['id','submitted_at','amount','status','category'],'submitted_at',20);$page=$payments->allPaged($q);$pending=$payments->pendingCount();
?><!doctype html><html lang="en"><head><?php require __DIR__.'/partials/head.php'; ?></head><body><div class="shell"><?php require __DIR__.'/partials/nav.php'; ?><main class="shell__main page-fade"><?php require __DIR__.'/partials/notice.php'; ?><?php require __DIR__.'/partials/admin_flash.php'; ?><header style="margin-bottom:var(--s-8)"><div class="eyebrow">Finance</div><h1>Fees verification</h1><p class="text-muted"><?= (int)$pending ?> submissions pending review. Approved proofs are automatically deleted after 24 hours.</p></header>
<form method="get" class="filter-bar" action="admin-payments.php"><input type="hidden" name="sort" value="<?= e($q->sort) ?>"><input type="hidden" name="dir" value="<?= e($q->dir) ?>"><div class="field"><label for="f_status">Status</label><select id="f_status" name="f_status"><option value="">All</option><?php foreach(['pending','approved','rejected'] as $s): ?><option value="<?= e($s) ?>" <?= $q->filter('status')===$s?'selected':'' ?>><?= e(ucfirst($s)) ?></option><?php endforeach; ?></select></div><div class="field"><label for="f_category">Category</label><select id="f_category" name="f_category"><option value="">All</option><?php foreach(['programme','examination'] as $c): ?><option value="<?= e($c) ?>" <?= $q->filter('category')===$c?'selected':'' ?>><?= e(ucfirst($c)) ?></option><?php endforeach; ?></select></div><div class="field"><label for="f_q">Search</label><input id="f_q" name="f_q" value="<?= e($q->filter('q')) ?>" placeholder="Reference, name or email"></div><button class="btn">Apply</button><a class="btn btn--ghost" href="admin-payments.php">Reset</a></form>
<div class="table-wrap"><table class="table"><thead><tr><th>Student</th><th>Reference</th><th>Category</th><?= sortable_th('Amount','amount',$q) ?><th>Type</th><th>Proof</th><?= sortable_th('Submitted','submitted_at',$q) ?><?= sortable_th('Status','status',$q) ?><th>Action</th></tr></thead><tbody><?php if($page['rows']===[]): ?><tr><td colspan="9" class="text-muted">No submissions match these filters.</td></tr><?php else: foreach($page['rows'] as $p): $status=(string)$p['status']; ?><tr><td><?= e((string)$p['name']) ?><br><small><?= e((string)$p['email']) ?></small></td><td><?= e((string)($p['reference']??'—')) ?></td><td><?= e(ucfirst((string)$p['category'])) ?></td><td><?= e(money((int)$p['amount'])) ?></td><td><?= e(ucfirst((string)$p['payment_type'])) ?></td><td><?php if(!empty($p['proof_deleted_at'])): ?>Deleted<?php else: ?><a href="view_proof.php?id=<?= (int)$p['id'] ?>" data-proof-link>Preview</a><?php endif; ?></td><td><?= e((string)$p['submitted_at']) ?></td><td><span class="badge <?= $status==='approved'?'badge--on':($status==='rejected'?'badge--off':'badge--gold') ?>"><?= e(ucfirst($status)) ?></span></td><td><?php if($status==='pending'&&$admin->can('payment.review')): ?><form method="post" class="row gap-2" data-confirm-modal data-modal-title="Confirm payment decision" data-modal-body="The decision will be recorded for this payment." data-modal-confirm="Confirm"><?= csrf_field() ?><input type="hidden" name="form_action" value="payment_status"><input type="hidden" name="payment_id" value="<?= (int)$p['id'] ?>"><button class="btn btn--gold btn--sm" name="status" value="approved">Approve</button><button class="btn btn--danger btn--sm" name="status" value="rejected">Reject</button></form><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; endif; ?></tbody></table></div><?= render_pager($q,(int)$page['total']) ?>
<?php if($admin->can('settings.manage')): ?><section class="card" style="margin-top:var(--s-10)"><div class="eyebrow">Configuration</div><h2>Payment details shown to students</h2><p class="card__hint">These details appear on the student fees page.</p><form method="post"><?= csrf_field() ?><input type="hidden" name="form_action" value="save_payment_settings"><div class="grid-2"><div class="field"><label for="bank_number">Bank account number</label><input id="bank_number" name="bank_number" value="<?= e($settings->bankNumber()) ?>" maxlength="64"></div><div class="field"><label for="lipa_number">Lipa number</label><input id="lipa_number" name="lipa_number" value="<?= e($settings->lipaNumber()) ?>" maxlength="64"></div></div><button class="btn btn--gold" style="margin-top:var(--s-5)">Save payment details</button></form></section><?php endif; ?>
</main></div><script src="assets/js/wisdom-ui.js" nonce="<?= e(nonce()) ?>" defer></script></body></html>
