<?php
declare(strict_types=1);
require __DIR__ . '/../config/bootstrap.php';
use Wisdom\Core\App; use Wisdom\Core\AppException; use Wisdom\Core\Csrf; use Wisdom\Core\Guard; use Wisdom\Core\Request; use Wisdom\Core\Session; use Wisdom\Services\UserService;
$admin=Guard::requirePermission('team.manage'); Guard::requirePasswordResetHandled(); $service=App::get(UserService::class); $active='admin-add-user'; $pageTitle='Add user';
if(Request::isPost()){
    Guard::throttle('admin.action',30,60);
    if(!Csrf::verifyRequest()){Session::flash('error','Your session expired. Please try again.');redirect('admin-add-user.php');}
    try{$service->createTeamMember($admin,Request::post('team_name'),Request::post('team_email'),Request::post('team_password'),Request::post('team_password_confirmation'),Request::post('team_role'));Session::flash('success','User created. They can sign in immediately with the credentials you set.');redirect('admin-users.php');}
    catch(AppException $e){Session::flash('error',$e->getMessage());redirect('admin-add-user.php');}
}
?><!doctype html><html lang="en"><head><?php require __DIR__.'/partials/head.php'; ?></head><body><div class="shell"><?php require __DIR__.'/partials/nav.php'; ?><main class="shell__main page-fade"><?php require __DIR__.'/partials/notice.php'; ?><?php require __DIR__.'/partials/admin_flash.php'; ?><header style="margin-bottom:var(--s-8)"><div class="eyebrow">People</div><h1>Add user</h1><p class="text-muted">Create an administrator or secretary account.</p></header><section class="card" style="max-width:720px"><form method="post" id="add-user-form" novalidate><?= csrf_field() ?><div class="field"><label for="team_role">Role</label><select id="team_role" name="team_role" required><option value="secretary">Secretary</option><option value="admin">Administrator</option></select></div><div class="grid-2 mt-6"><div class="field"><label for="team_name">Full name</label><input id="team_name" name="team_name" maxlength="255" required autocomplete="name"></div><div class="field"><label for="team_email">Email</label><input id="team_email" name="team_email" type="email" maxlength="254" required autocomplete="email"></div><div class="field"><label for="team_password">Password</label><div class="pw-wrap"><input id="team_password" name="team_password" type="password" minlength="8" maxlength="72" required autocomplete="new-password"><button class="pw-toggle" type="button" data-password-toggle="team_password" aria-label="Show password" aria-pressed="false">Show</button></div></div><div class="field"><label for="team_password_confirmation">Confirm password</label><div class="pw-wrap"><input id="team_password_confirmation" name="team_password_confirmation" type="password" minlength="8" maxlength="72" required autocomplete="new-password"><button class="pw-toggle" type="button" data-password-toggle="team_password_confirmation" aria-label="Show password" aria-pressed="false">Show</button></div><small id="password-mismatch" class="text-muted" role="alert" hidden>Values do not match.</small></div></div><div class="row gap-3 mt-6"><button class="btn btn--gold" type="submit">Create user</button><a class="btn btn--ghost" href="admin-users.php">Cancel</a></div></form></section></main></div><script nonce="<?= e(nonce()) ?>">
(() => { const form=document.getElementById('add-user-form'), p=document.getElementById('team_password'), c=document.getElementById('team_password_confirmation'), msg=document.getElementById('password-mismatch'); const check=()=>{const bad=c.value!==''&&p.value!==c.value;msg.hidden=!bad;c.setCustomValidity(bad?'Values do not match.':'');return !bad;};p.addEventListener('input',check);c.addEventListener('input',check);form.addEventListener('submit',e=>{if(!check()||!form.reportValidity())e.preventDefault();});document.querySelectorAll('[data-password-toggle]').forEach(b=>b.addEventListener('click',()=>{const i=document.getElementById(b.dataset.passwordToggle),show=i.type==='password';i.type=show?'text':'password';b.textContent=show?'Hide':'Show';b.setAttribute('aria-pressed',show?'true':'false');b.setAttribute('aria-label',show?'Hide password':'Show password');}));})();
</script><script src="assets/js/wisdom-ui.js" nonce="<?= e(nonce()) ?>" defer></script></body></html>
