<?php
declare(strict_types=1);
require __DIR__ . '/../config/bootstrap.php';
use Wisdom\Core\App; use Wisdom\Core\AppException; use Wisdom\Core\Csrf; use Wisdom\Core\Guard; use Wisdom\Core\Request; use Wisdom\Core\Session; use Wisdom\Services\PasswordResetService;
$admin=Guard::requirePermission('user.manage'); Guard::requirePasswordResetHandled(); $service=App::get(PasswordResetService::class); $active='admin-password-resets'; $pageTitle='Password reset requests';
if(Request::isPost()){
    Guard::throttle('admin.action',30,60);
    if(!Csrf::verifyRequest()){Session::flash('error','Your session expired. Please try again.');redirect('admin-password-resets.php');}
    try{switch(Request::post('form_action')){case 'approve_reset_request':[$user,$temp]=$service->approve($admin,Request::intPost('request_id'));Session::set('_temp_password_flash',['name'=>$user->getName(),'email'=>$user->getEmail(),'temp'=>$temp]);Session::flash('success','Reset approved. A temporary password was generated.');break;case 'reject_reset_request':$service->reject($admin,Request::intPost('request_id'));Session::flash('success','Reset request rejected.');break;default:throw new AppException('Unknown action.');}}catch(AppException $e){Session::flash('error',$e->getMessage());}redirect('admin-password-resets.php');
}
$rows=$service->pendingRequests();$temporary=Session::get('_temp_password_flash');if(is_array($temporary))Session::remove('_temp_password_flash');
?><!doctype html><html lang="en"><head><?php require __DIR__.'/partials/head.php'; ?></head><body><div class="shell"><?php require __DIR__.'/partials/nav.php'; ?><main class="shell__main page-fade"><?php require __DIR__.'/partials/notice.php'; ?><?php require __DIR__.'/partials/admin_flash.php'; ?><?php if(is_array($temporary)): ?><section class="card" style="border-left:5px solid var(--gold-600);margin-bottom:var(--s-6)"><div class="eyebrow">Temporary password — share this with the user</div><h2><?= e((string)$temporary['name']) ?> · <?= e((string)$temporary['email']) ?></h2><div class="row gap-2"><code id="temporary-password"><?= e((string)$temporary['temp']) ?></code><button type="button" class="copy-btn" data-copy="temporary-password">Copy</button></div><p class="text-muted">Shown once. The user must change it at next login.</p></section><?php endif; ?><header style="margin-bottom:var(--s-8)"><div class="eyebrow">Security</div><h1>Password reset requests</h1><p class="text-muted">Approve to generate a temporary password, or reject to leave the account unchanged.</p></header><section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Requested</th><th>User</th><th>Email</th><th>Note</th><th>Action</th></tr></thead><tbody><?php if($rows===[]): ?><tr><td colspan="5" class="text-muted">No pending password-reset requests.</td></tr><?php else: foreach($rows as $r): ?><tr><td><?= e((string)$r['created_at']) ?></td><td><?= e((string)$r['user_name']) ?></td><td><?= e((string)$r['user_email']) ?></td><td><?= $r['note']===''?'—':e((string)$r['note']) ?></td><td><div class="row gap-2"><form method="post" data-confirm-modal data-modal-title="Approve reset?" data-modal-body="A temporary password will be generated." data-modal-confirm="Approve"><?= csrf_field() ?><input type="hidden" name="form_action" value="approve_reset_request"><input type="hidden" name="request_id" value="<?= (int)$r['id'] ?>"><button class="btn btn--sm">Approve</button></form><form method="post" data-confirm-modal data-modal-title="Reject reset?" data-modal-body="The account will remain unchanged." data-modal-confirm="Reject" data-modal-danger="1"><?= csrf_field() ?><input type="hidden" name="form_action" value="reject_reset_request"><input type="hidden" name="request_id" value="<?= (int)$r['id'] ?>"><button class="btn btn--danger btn--sm">Reject</button></form></div></td></tr><?php endforeach; endif; ?></tbody></table></div></section></main></div><script src="assets/js/wisdom-ui.js" nonce="<?= e(nonce()) ?>" defer></script></body></html>
