<?php
declare(strict_types=1);
require __DIR__ . '/../config/bootstrap.php';
use Wisdom\Core\App; use Wisdom\Core\AppException; use Wisdom\Core\Csrf; use Wisdom\Core\Guard; use Wisdom\Core\ListQuery; use Wisdom\Core\Request; use Wisdom\Core\Session; use Wisdom\Models\Exam; use Wisdom\Repositories\ExamRepository; use Wisdom\Services\ExamService;
$admin=Guard::requirePermission('exam.manage'); Guard::requirePasswordResetHandled(); $service=App::get(ExamService::class); $repo=App::get(ExamRepository::class); $active='admin-exams'; $pageTitle='Examinations';
if(Request::isPost()){
    Guard::throttle('admin.action',60,60);
    if(!Csrf::verifyRequest()){Session::flash('error','Your session expired. Please try again.');redirect('admin-exams.php');}
    try{if(Request::post('form_action')!=='save_exam')throw new AppException('Unknown action.');$service->record($admin,Request::intPost('user_id'),Request::post('subject_code'),Request::post('exam_number'),Request::post('subject_name'),(float)Request::post('weight'),Request::post('result')===''?null:(float)Request::post('result'),Request::post('grade')===''?null:Request::post('grade'),Request::post('exam_status'));Session::flash('success','Exam record saved.');}catch(AppException $e){Session::flash('error',$e->getMessage());}
    redirect('admin-exams.php');
}
$q=ListQuery::fromRequest(['id','user','subject_name','subject_code','result','status'],'id',25);$page=$repo->paginateWithStudent($q);
?><!doctype html><html lang="en"><head><?php require __DIR__.'/partials/head.php'; ?></head><body><div class="shell"><?php require __DIR__.'/partials/nav.php'; ?><main class="shell__main page-fade"><?php require __DIR__.'/partials/notice.php'; ?><?php require __DIR__.'/partials/admin_flash.php'; ?><header style="margin-bottom:var(--s-8)"><div class="eyebrow">Examinations</div><h1>Enter results</h1><p class="text-muted">Search for a student, select a subject, and save. Records are listed below.</p></header>
<section class="card" style="margin-bottom:var(--s-8)"><form method="post" novalidate><?= csrf_field() ?><input type="hidden" name="form_action" value="save_exam"><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:var(--s-4)">
<div class="field"><label for="student-query">Student</label><div class="ac-wrap" id="exam-student" data-endpoint="admin_suggest.php" data-extra='{"type":"student"}'><input id="student-query" class="ac-input" type="text" autocomplete="off" placeholder="Type a student name" required><input type="hidden" name="user_id" required><button type="button" class="ac-clear" aria-label="Clear student">×</button><ul class="ac-list" role="listbox" aria-label="Student suggestions"></ul></div></div>
<div class="field"><label for="subject-query">Subject</label><div class="ac-wrap" id="exam-subject" data-endpoint="admin_suggest.php" data-extra='{"type":"subject"}'><input id="subject-query" class="ac-input" type="text" autocomplete="off" placeholder="Type a subject" required><input type="hidden" name="subject_name" required><button type="button" class="ac-clear" aria-label="Clear subject">×</button><ul class="ac-list" role="listbox" aria-label="Subject suggestions"></ul></div></div>
<div class="field"><label for="subject_code">Subject code</label><input id="subject_code" name="subject_code" maxlength="30" required></div><div class="field"><label for="exam_number">Exam number</label><input id="exam_number" name="exam_number" maxlength="50" required></div><div class="field"><label for="weight">Weight</label><input id="weight" name="weight" type="number" min="0" max="1000" step="0.01" value="100" required></div><div class="field"><label for="result">Result</label><input id="result" name="result" type="number" min="0" max="100" step="0.01"></div><div class="field"><label for="grade">Grade</label><input id="grade" name="grade" maxlength="5"></div><div class="field"><label for="exam_status">Status</label><select id="exam_status" name="exam_status"><?php foreach(Exam::STATUSES as $status): ?><option value="<?= e($status) ?>"><?= e(ucfirst($status)) ?></option><?php endforeach; ?></select></div>
</div><button class="btn btn--gold" style="margin-top:var(--s-5)">Save exam record</button></form></section>
<section class="card"><div class="card__head"><h2 class="card__title">Exam records</h2><span class="text-muted"><?= (int)$page['total'] ?> total</span></div><div class="table-wrap"><table class="table"><thead><tr><?= sortable_th('Student','user',$q) ?><?= sortable_th('Code','subject_code',$q) ?><th>Exam no.</th><?= sortable_th('Subject','subject_name',$q) ?><th>Weight</th><?= sortable_th('Result','result',$q) ?><th>Grade</th><?= sortable_th('Status','status',$q) ?></tr></thead><tbody><?php if($page['rows']===[]): ?><tr><td colspan="8" class="text-muted">No exam records match those filters.</td></tr><?php else: foreach($page['rows'] as $x): ?><tr><td><?= e((string)$x['name']) ?></td><td><?= e((string)$x['subject_code']) ?></td><td><?= e((string)$x['exam_number']) ?></td><td><?= e((string)$x['subject_name']) ?></td><td><?= e((string)$x['weight']) ?></td><td><?= $x['result']===null?'—':e((string)$x['result']) ?></td><td><?= $x['grade']===null?'—':e((string)$x['grade']) ?></td><td><?= e(ucfirst((string)$x['status'])) ?></td></tr><?php endforeach; endif; ?></tbody></table></div><?= render_pager($q,(int)$page['total']) ?></section>
</main></div><script src="assets/js/wisdom-autocomplete.js" nonce="<?= e(nonce()) ?>" defer></script><script src="assets/js/wisdom-ui.js" nonce="<?= e(nonce()) ?>" defer></script><script nonce="<?= e(nonce()) ?>">document.addEventListener('DOMContentLoaded',()=>{for(const [id,key] of [['exam-student','user_id'],['exam-subject','subject_name']]){const wrap=document.getElementById(id),hidden=wrap.querySelector('input[type=hidden]');wrap.addEventListener('ac:selected',e=>hidden.value=e.detail.value);wrap.addEventListener('ac:cleared',()=>hidden.value='');}});</script></body></html>
