<?php
declare(strict_types=1);
require __DIR__ . '/../config/bootstrap.php';
use Wisdom\Core\App; use Wisdom\Core\AppException; use Wisdom\Core\Csrf; use Wisdom\Core\Guard; use Wisdom\Core\Request; use Wisdom\Core\Session; use Wisdom\Services\NoticeService;
$admin=Guard::requirePermission('admin.access'); Guard::requirePasswordResetHandled(); $service=App::get(NoticeService::class); $active='admin-notices'; $pageTitle='Notices';
if(Request::isPost()){
    Guard::throttle('admin.action',30,60);
    if(!Csrf::verifyRequest()){Session::flash('error','Your session expired. Please try again.');redirect('admin-notices.php');}
    try{if(!$admin->can('notice.manage'))throw new AppException('You do not have permission to manage notices.');switch(Request::post('form_action')){case 'create_notice':$service->create($admin,Request::post('notice_title'),Request::post('notice_body'),Request::intPost('notice_duration')?:24);Session::flash('success','Notice published.');break;case 'deactivate_notice':$service->deactivate($admin,Request::intPost('notice_id'));Session::flash('success','Notice removed.');break;default:throw new AppException('Unknown action.');}}catch(AppException $e){Session::flash('error',$e->getMessage());}
    redirect('admin-notices.php');
}
$notices=$admin->can('notice.manage')?$service->all():[];
?><!doctype html><html lang="en"><head><?php require __DIR__.'/partials/head.php'; ?></head><body><div class="shell"><?php require __DIR__.'/partials/nav.php'; ?><main class="shell__main page-fade"><?php require __DIR__.'/partials/notice.php'; ?><?php require __DIR__.'/partials/admin_flash.php'; ?><header style="margin-bottom:var(--s-8)"><div class="eyebrow">Communication</div><h1>Notices</h1><p class="text-muted">Publish notices for signed-in users. Authors do not see their own notices.</p></header>
<?php if($admin->can('notice.manage')): ?><section class="card" style="margin-bottom:var(--s-8)"><form method="post"><?= csrf_field() ?><input type="hidden" name="form_action" value="create_notice"><div class="field"><label for="notice_title">Title</label><input id="notice_title" name="notice_title" maxlength="150" required></div><div class="field mt-4"><label for="notice_body">Body</label><textarea id="notice_body" name="notice_body" maxlength="5000" required></textarea></div><div class="field mt-4"><label for="notice_duration">Display duration</label><select id="notice_duration" name="notice_duration"><option value="24">24 hours (1 day)</option><option value="48">48 hours (2 days)</option><option value="72">72 hours (3 days)</option><option value="168">168 hours (1 week)</option></select></div><button class="btn btn--gold mt-4" type="submit">Publish notice</button></form></section>
<section class="card"><div class="card__head"><h2 class="card__title">Recent notices</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Created</th><th>Title</th><th>Expires</th><th>Posted by</th><th>Status</th><th></th></tr></thead><tbody><?php if($notices===[]): ?><tr><td colspan="6" class="text-muted">No notices yet.</td></tr><?php else: foreach($notices as $n): ?><tr><td><?= e((string)$n['created_at']) ?></td><td><?= e((string)$n['title']) ?></td><td><?= empty($n['expires_at'])?'Never':e(date('j M · H:i',strtotime((string)$n['expires_at']))) ?></td><td><?= e((string)($n['creator_name']??'System')) ?></td><td><?= (int)$n['is_active']?'Active':'Inactive' ?></td><td><?php if((int)$n['is_active']): ?><form method="post" data-confirm-modal data-modal-title="Deactivate this notice?" data-modal-body="The notice will be hidden from signed-in users." data-modal-confirm="Deactivate" data-modal-danger="1"><?= csrf_field() ?><input type="hidden" name="form_action" value="deactivate_notice"><input type="hidden" name="notice_id" value="<?= (int)$n['id'] ?>"><button class="btn btn--danger btn--sm">Deactivate</button></form><?php endif; ?></td></tr><?php endforeach; endif; ?></tbody></table></div></section><?php endif; ?>
</main></div><script src="assets/js/wisdom-ui.js" nonce="<?= e(nonce()) ?>" defer></script></body></html>
